<?php

/**
 * @file
 * File for the Cloudinary module.
 */

/**
 * Sample file on cloudinary for image effect preview.
 */
define('CLOUDINARY_SAMPLE', 'cloudinary://drupal_sample.png');

/**
 * Url prefix of cloudinary preview image.
 */
define('CLOUDINARY_PREVIEW_IMAGE_PREFIX', 'http://res.cloudinary.com/demo/image/upload/');

/**
 * Effects for effects param visible states.
 */
define('CLOUDINARY_VISIBLE_STATES_EFFECT', 'sepia,brightness,saturation,hue,oil_paint,vignette,pixelate,pixelate_faces,gradient_fade,blur,tilt_shift,sharpen,unsharp_mask,pixelate_region,red,blue,green,contrast,vibrance,fill_light,blur_region,blur_faces,make_transparent,trim,shadow,colorize');

/**
 * Crop mode for gravity visible states.
 */
define('CLOUDINARY_VISIBLE_STATES_CROP', 'fill,crop,thumb,pad,lfill,lpad,mpad');

/**
 * Implements hook_theme().
 */
function cloudinary_theme() {
  return array(
    'cloudinary_crop_summary' => array(
      'variables' => array(
        'data' => NULL,
      ),
    ),
    'cloudinary_image_style_preview' => array(
      'function' => 'theme_cloudinary_image_style_preview',
      'variables' => array(
        'original' => NULL,
        'preview' => NULL,
      ),
    ),
  );
}

use Drupal\Core\Url;

/**
 * Theme function for Cloudinary effect.
 */
function theme_cloudinary_crop_summary($variables) {
  $attributes = 'None';
  $data = cloudinary_preprocess_transformation($variables['data']);
  if (!empty($data)) {
    $attribute = array();
    foreach ($data as $key => $value) {
      if (is_array($value)) {
        $value = implode('.', array_filter($value));
      }
      $attribute[] = "$key: $value";
    }
    $attributes = implode(', ', $attribute);
  }

  return t('Image will have cloudinary effects applied with attributes : @attributes', array('@attributes' => $attributes));
}

/**
 * Returns HTML for a cloudinary preview of an image style.
 *
 * @ingroup themeable
 */
function theme_cloudinary_image_style_preview($variables) {
  $sample_width = 160;
  $sample_height = 160;
  // Set up original file information.
  $original = $variables['original'];
  $original_image = cloudinary_stream_wrapper_remote_image_info($original);
  if ($original_image['width'] > $original_image['height']) {
    $original_width = min($original_image['width'], $sample_width);
    $original_height = round($original_width / $original_image['width'] * $original_image['height']);
  }
  else {
    $original_height = min($original_image['height'], $sample_height);
    $original_width = round($original_height / $original_image['height'] * $original_image['width']);
  }
  $original_attributes = array_intersect_key($original_image, array('width' => '', 'height' => ''));
  $original_attributes['style'] = 'width: ' . $original_width . 'px; height: ' . $original_height . 'px;';
  // Set up preview file information.
  $preview = $variables['preview'];
  $preview_image = cloudinary_stream_wrapper_remote_image_info($preview);
  if ($preview_image['width'] > $preview_image['height']) {
    $preview_width = min($preview_image['width'], $sample_width);
    $preview_height = round($preview_width / $preview_image['width'] * $preview_image['height']);
  }
  else {
    $preview_height = min($preview_image['height'], $sample_height);
    $preview_width = round($preview_height / $preview_image['height'] * $preview_image['width']);
  }
  $preview_attributes = array_intersect_key($preview_image, array('width' => '', 'height' => ''));
  $preview_attributes['style'] = 'width: ' . $preview_width . 'px; height: ' . $preview_height . 'px;';

  $original_image = array(
    '#theme' => 'image',
    '#uri' => $original,
    '#width' => $original_width,
    '#height' => $original_height,
  );
  $cloudinary_original_image = \Drupal::service('renderer')->render($original_image);

  $preview_image = array(
    '#theme' => 'image',
    '#uri' => $preview,
    '#width' => $preview_width,
    '#height' => $preview_height,
  );
  $cloudinary_preview_image = \Drupal::service('renderer')->render($preview_image);

//  http://res.cloudinary.com/demo/image/upload/a_auto_left.auto_right.exif.hflip.ignore.vflip,b_2,bo_2px_solid_rgb:000,h_2,o_2,r_2,w_100/a_2/sample.jpg
  $output = '<div class="image-style-preview preview clearfix">';
  $output .= '<div class="preview-image-wrapper">';
  $url = Url::fromUri($original);
  $original_link = \Drupal::l(t('view actual size'), $url);
  $output .= t('original') . ' (' . $original_link . ')';

  $output .= '<div class="preview-image original-image" style="' . $original_attributes['style'] . '">';
  $output .= '<a href="' . $original . '">' . $cloudinary_original_image . '</a>';
  $output .= '<div class="height" style="height: ' . $original_height . 'px"><span>' . $original_image['#height'] . 'px</span></div>';
  $output .= '<div class="width" style="width: ' . $original_width . 'px"><span>' . $original_image['#width'] . 'px</span></div>';
  $output .= '</div>';
  $output .= '</div>';
  // Build the preview of the image style.
  $output .= '<div class="preview-image-wrapper">';
  $url = Url::fromUri($preview);
  $preview_link = \Drupal::l(t('view actual size'), $url);
  $output .= t('transformation') . ' (' . $preview_link . ')';

  $output .= '<div class="preview-image modified-image" style="' . $preview_attributes['style'] . '">';
  $output .= '<a href="' . $preview . '">' . $cloudinary_preview_image . '</a>';
  $output .= '<div class="height" style="height: ' . $preview_height . 'px"><span>' . $preview_image['#height'] . 'px</span></div>';
  $output .= '<div class="width" style="width: ' . $preview_width . 'px"><span>' . $preview_image['#width'] . 'px</span></div>';
  $output .= '</div>';
  $output .= '</div>';
  $output .= '</div>';

  return $output;
}

/**
 * Implements hook_cloudinary_stream_wrapper_transformation().
 */
function cloudinary_cloudinary_stream_wrapper_transformation() {
  $path = drupal_get_path('module', 'cloudinary');

  return array(
    'cloudinary_crop' => array(
      'title' => t('Cloudinary crop'),
      'callback' => 'cloudinary_transformation_cloudinary_crop',
      'file' => $path . '/includes/cloudinary.transformation.cloudinary.inc',
    ),
    'image_crop' => array(
      'title' => t('Crop'),
      'callback' => 'cloudinary_transformation_image_crop',
      'file' => $path . '/includes/cloudinary.transformation.drupal.inc',
    ),
    'image_desaturate' => array(
      'title' => t('Desaturate'),
      'callback' => 'cloudinary_transformation_image_desaturate',
    ),
    'image_resize' => array(
      'title' => t('Resize'),
      'callback' => 'cloudinary_transformation_image_resize',
    ),
    'image_rotate' => array(
      'title' => t('Rotate'),
      'callback' => 'cloudinary_transformation_image_rotate',
    ),
    'image_scale' => array(
      'title' => t('Scale'),
      'callback' => 'cloudinary_transformation_image_scale',
    ),
    'image_scale_and_crop' => array(
      'title' => t('Scale and crop'),
      'callback' => 'cloudinary_transformation_image_scale_and_crop',
    ),
  );
}

/**
 * Convert image effect to special structure for cloudinary style.
 */
function cloudinary_transformation_image($data, $extra = NULL) {
  if ($extra) {
    if (is_array($extra)) {
      $data = array_merge($data, $extra);
    }
    else {
      $data['crop'] = $extra;
    }
  }

  $type = CLOUDINARY_STREAM_WRAPPER_TRANSFORMATION_NEW;
  if (isset($data['type'])) {
    $type = $data['type'];
    unset($data['type']);
  }

  return array('type' => $type, 'data' => $data);
}

/**
 * Ajax callback for cloudinary image preview on effect edit form.
 */
function cloudinary_crop_form_preview_callback($form, $form_state) {
  $data = cloudinary_from_image_effect_prepare($form_state['values']['data']);
  $form['data']['cloudinary']['preview']['thumbnail']['#markup'] = cloudinary_crop_form_preview($data);

  return $form['data']['cloudinary']['preview']['thumbnail'];
}

/**
 * Generate cloudinary image preview for effect edit form.
 */
function cloudinary_crop_form_preview($data) {
  $filename = 'sample.jpg';

  if (isset($data['gravity'])) {
    switch ($data['gravity']) {
      case 'face':
      case 'face:center':
      case 'rek_face':
        $filename = 'bike.jpg';
        break;

      case 'faces':
      case 'faces:center':
      case 'rek_faces':
        $filename = 'couple.jpg';
        break;
    }
  }

  if (isset($data['effect'])) {
    switch ($data['effect']) {
      case 'redeye':
      case 'rek_redeye':
        $filename = 'itaib_redeye_msjmif.jpg';
        break;

      case 'pixelate_faces':
      case 'blur_faces':
        $filename = 'couple.jpg';
        break;
    }
  }

  $original = CLOUDINARY_PREVIEW_IMAGE_PREFIX . $filename;
  $preview = $original;

  $data = cloudinary_prepare_transformation($data);
  $trans = \Cloudinary::generate_transformation_string($data);
  if ($trans) {
    $preview = CLOUDINARY_PREVIEW_IMAGE_PREFIX . trim($trans, '/') . '/' . $filename;
  }

  $styles = array('original' => $original, 'preview' => $preview);
  // @FIXME
// theme() has been renamed to _theme() and should NEVER be called directly.
// Calling _theme() directly can alter the expected output and potentially
// introduce security issues (see https://www.drupal.org/node/2195739). You
// should use renderable arrays instead.
// 
// 
// @see https://www.drupal.org/node/2195739
  return _theme('cloudinary_image_style_preview', $styles);

}

/**
 * Prepare cloudinary transformation with attributes.
 *
 * Return multiple transformations if angle set.
 */
function cloudinary_prepare_transformation($data, $only = TRUE) {
  $data = cloudinary_preprocess_transformation($data);
  // Rotation Angle.
  if (isset($data['angle']) || isset($data['angles'])) {
    if (isset($data['crop']) && $data['crop'] != 'crop') {
      unset($data['crop']);
    }
    if (isset($data['angle']) && count($data) > 1) {
      $angle = $data['angle'];
      unset($data['angle']);
      if (isset($data['angles'])) {
        $data['angle'] = array_values(array_filter($data['angles']));
        unset($data['angles']);
      }

      $new_data = array($data);
      $new_data[] = array('angle' => $angle);

      if ($only !== TRUE) {
        $new_data['multiple'] = TRUE;
      }

      return $new_data;
    }
  }

  return $data;
}

/**
 * Preprocess cloudinary transformation.
 *
 * Unset empty value fields.
 *
 * Merge field value to cloudinary format.
 */
function cloudinary_preprocess_transformation($data) {
  $data = array_filter($data);
  // Merge border with and border color.
  if (isset($data['border_width'])) {
    $border = $data['border_width'] . 'px_solid_rgb:';
    $border_color = '000';
    // Check and convert short #FFFFFF syntax to full #FFF syntax.
    if (isset($data['border_color'])) {
      $bc = $data['border_color'];
      $len = strlen($bc);
      if ($len == 7 || $len == 4) {
        $border_color = substr($bc, 1);
        if ($len == 7 && $bc[0] == $bc[1] && $bc[2] == $bc[3] && $bc[4] == $bc[5]) {
          $border_color = $bc[0] . $bc[2] . $bc[4];
        }
      }
    }
    // Append border color to border.
    $border .= $border_color;
    $data['border'] = $border;
    // Unset unused attributes.
    unset($data['border_width'], $data['border_color']);
  }
  // Meger effect with effects param.
  if (isset($data['effect']) && isset($data['effects_param'])) {
    $data['effect'] .= ':' . $data['effects_param'];
  }

  return $data;
}

/**
 * Upload sample image to cloudinary if no exist.
 *
 * Replace image_style_preview_image to cloudinary sample image.
 */
function cloudinary_upload_sample() {
  if (!file_exists(CLOUDINARY_SAMPLE)) {
    if (file_save_data(file_get_contents(drupal_get_path('module', 'image') . '/sample.png'), CLOUDINARY_SAMPLE)) {
      $config = \Drupal::service('config.factory')->getEditable('image.settings');
      $config->set('image.settings.preview_image', CLOUDINARY_SAMPLE);
      $config->save();
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for image_style_form().
 *
 * Alters the image style form.
 *
 * @see image_style_form()
 */
function cloudinary_form_image_style_form_alter(&$form, &$from_state) {
  // Prepare and upload sample image.
  cloudinary_upload_sample();
  // Remove cache flag.
  $form['preview']['#markup'] = preg_replace('#\?(cache_bypass=)?\d{10}#', '', $form['preview']['#markup']);
}

///**
// * Implements hook_form_FORM_ID_alter() for image_effect_form().
// *
// * Alters the image style form.
// *
// * @see image_effect_form()
// */
//function cloudinary_form_image_effect_form_alter(&$form, &$from_state) {
//  if (!isset($form['data']['cloudinary'])) {
//    return;
//  }

//  if (isset($form['#submit']) && !empty($form['#submit'])) {
//    array_unshift($form['#submit'], 'cloudinary_form_image_effect_submit');
//  }
//  else {
//    $form['#submit'] = array('cloudinary_form_image_effect_submit');
//  }
//}

/**
 * Prepare cloudinary image effect before save.
 */
function cloudinary_from_image_effect_prepare($data) {
  // Unset border_color if border_width is empty.
  if (empty($data['border_width'])) {
    $data['border_color'] = '';
  }
  // Unset angles if automatic_rotation unchecked.
  if (empty($data['automatic_rotation'])) {
    $data['angles'] = array();
  }
  // Unset effects_param if effect doesn't have param.
  $effect_param_effects = explode(',', CLOUDINARY_VISIBLE_STATES_EFFECT);

  if (!in_array($data['effect'], $effect_param_effects)) {
    $data['effects_param'] = '';
  }
  // Unset gravity if mode doesn't have.
  $gravity_corp_modes = explode(',', CLOUDINARY_VISIBLE_STATES_CROP);

  if (!in_array($data['crop'], $gravity_corp_modes)) {
    $data['gravity'] = '';
  }
  // Unset x,y if crop mode isn't crop.
  if ($data['crop'] != 'crop') {
    $data['x'] = $data['y'] = '';
  }

  return $data;
}

/**
 * Submit handler for adding a cloudinary effect to an image style.
 */
function cloudinary_form_image_effect_submit($form, &$form_state) {
  $form_state['values']['data'] = cloudinary_from_image_effect_prepare($form_state['values']['data']);
}

/**
 * Get value from array by key with default value.
 */
function cloudinary_value_get($data, $key, $default = '') {
  return isset($data[$key]) ? $data[$key] : $default;
}

/**
 * Build options for corp modes.
 */
function _cloudinary_options_crop($key = NULL) {
  $data = array(
    '' => t('None'),
    'scale' => t('Scale'),
    'limit' => t('Limit'),
    'fill' => t('Fill'),
    'fit' => t('Fit'),
    'crop' => t('Crop'),
    'thumb' => t('Thumb'),
    'pad' => t('Pad'),
    'lfill' => t('Limited Fill'),
    'lpad' => t('Limit & Pad'),
    'mfit' => t('Fit (Scale Up)'),
    'mpad' => t('Pad (No Scale)'),
    'imagga_crop' => t('Imagga crop'),
    'imagga_scale' => t('Imagga scale'),
  );

  if (!is_null($key) && isset($data[$key])) {
    return $data[$key];
  }

  return $data;
}

/**
 * Build options for gravity.
 */
function _cloudinary_options_gravity($key = NULL) {
  $data = array(
    '' => t('None'),
    'face' => t('Face'),
    'faces' => t('Faces'),
    'north_west' => t('North West'),
    'north' => t('North'),
    'north_east' => t('North East'),
    'east' => t('East'),
    'center' => t('Center'),
    'west' => t('West'),
    'south_west' => t('South West'),
    'south' => t('South'),
    'south_east' => t('South East'),
    'face:center' => t('Face (Center)'),
    'faces:center' => t('Faces (Center)'),
    'custom' => t('Custom'),
    'xy_center' => t('XY Center'),
    'rek_face' => t('ReKognition: Face'),
    'rek_faces' => t('ReKognition: Faces'),
    'rek_eyes' => t('ReKognition: Eyes'),
  );

  if (!is_null($key) && isset($data[$key])) {
    return $data[$key];
  }

  return $data;
}

/**
 * Build options for angles.
 */
function _cloudinary_options_angles($key = NULL) {
  $data = array(
    'auto_left' => t('Auto left'),
    'auto_right' => t('Auto right'),
    'exif' => t('Use EXIF data'),
    'hflip' => t('Horizontal flip'),
    'ignore' => t('Ignore'),
    'vflip' => t('Vertical flip'),
  );

  if (!is_null($key) && isset($data[$key])) {
    return $data[$key];
  }

  return $data;
}

/**
 * Build options for effect.
 */
function _cloudinary_options_effect($key = NULL) {
  $data = array(
    '' => t('None'),
    'grayscale' => t('Grayscale'),
    'blackwhite' => t('Blackwhite'),
    'sepia' => t('Sepia'),
    'brightness' => t('Brightness'),
    'saturation' => t('Saturation'),
    'hue' => t('Hue'),
    'oil_paint' => t('Oil paint'),
    'vignette' => t('Vignette'),
    'pixelate' => t('Pixelate'),
    'pixelate_faces' => t('Pixelate faces'),
    'gradient_fade' => t('Gradient fade'),
    'blur' => t('Blur'),
    'improve' => t('Improve'),
    'tilt_shift' => t('Tilt shift'),
    'sharpen' => t('Sharpen'),
    'unsharp_mask' => t('Unsharp mask'),
    'pixelate_region' => t('Pixelate region'),
    'red' => t('Red'),
    'blue' => t('Blue'),
    'green' => t('Green'),
    'contrast' => t('Contrast'),
    'vibrance' => t('Vibrance'),
    'auto_color' => t('Auto color'),
    'auto_brightness' => t('Auto brightness'),
    'auto_contrast' => t('Auto contrast'),
    'fill_light' => t('Fill light'),
    'blur_region' => t('Blur region'),
    'blur_faces' => t('Blur faces'),
    'make_transparent' => t('Make transparent'),
    'trim' => t('Trim'),
    'mask' => t('Mask'),
    'shadow' => t('Shadow'),
    'negate' => t('Negate'),
    'screen' => t('Screen'),
    'multiply' => t('Multiply'),
    'colorize' => t('Colorize'),
    'redeye' => t('Remove red eyes'),
    'rek_redeye' => t('ReKognition: Remove red eyes'),
    'overlay' => t('Overlay'),
    'gamma' => t('Gamma'),
  );

  if (!is_null($key) && isset($data[$key])) {
    return $data[$key];
  }

  return $data;
}

/**
 * Build group conditions of visible states.
 */
function _cloudinary_build_visible_states($visible) {
  $data = array();
  $datas = explode(',', $visible);
  foreach ($datas as $value) {
    $data[] = array('value' => $value);
  }
  return $data;
}
